import Head from "next/head";
import React, { useState, useEffect, Suspense, useCallback } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/Components/Navbar/Navbar";
import IntroSection from "@/Components/IntroSection/IntroSection";
import ProductSection from "@/Components/ProductSection/ProductSection";
import Showcase from "@/Components/Showcase/Showcase";
import AnimatedCursor from "react-animated-cursor";
import Footer from "@/Components/Footer/Footer";

const Spline = React.lazy(() => import("@splinetool/react-spline"));

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobile, setIsMobile] = useState(false);
  const [hasSplineError, setHasSplineError] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      React.startTransition(() => {
        setIsScrolled(window.scrollY > 5);
      });
    };

    let resizeTimeout;
    const handleResize = () => {
      clearTimeout(resizeTimeout);
      resizeTimeout = setTimeout(() => {
        React.startTransition(() => {
          setIsMobile(window.innerWidth <= 768);
        });
      }, 150);
    };

    window.addEventListener("scroll", handleScroll);
    window.addEventListener("resize", handleResize);

    handleResize(); // Check initial window size

    return () => {
      window.removeEventListener("scroll", handleScroll);
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  const handleSplineError = useCallback(() => {
    setHasSplineError(true);
  }, []);

  return (
    <>
      <Head>
        <title>Coca‑Cola</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {!isMobile && (
          <AnimatedCursor
            innerSize={18}
            outerSize={18}
            color="240, 230, 230"
            outerAlpha={0.2}
            innerScale={0.7}
            outerScale={5}
          />
        )}
        <Navbar />
        <div className={styles.introDummy}></div>
        <div className={styles.spline}>
          {!hasSplineError ? (



            <Suspense fallback={<div>Loading...</div>}>
              <Spline scene={isMobile?"https://prod.spline.design/KXrq5-wwjBYGFkQD/scene.splinecode":"https://prod.spline.design/cW9T8nT4Aoyqpwgd/scene.splinecode"} onError={handleSplineError} />
            </Suspense>
          ) : (
            <div>Failed to load Spline component.</div>
          )}
        </div>
        <div className={`${styles.scrollIcon} ${isScrolled ? styles.hidden : ""}`}>
          <div className={styles.mouse}></div>
        </div>
        <IntroSection />
        <Showcase />
        <ProductSection />
        <Footer />
      </main>
    </>
  );
}
