import Head from "next/head";
import React, { useState, useEffect, Suspense } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/Components/Navbar/Navbar";
import IntroSection from "@/Components/IntroSection/IntroSection";
import ProductSection from "@/Components/ProductSection/ProductSection";
import Showcase from "@/Components/Showcase/Showcase";
import AnimatedCursor from "react-animated-cursor"
import Footer from "@/Components/Footer/Footer";
import ScrollAnimation from 'react-animate-on-scroll';

const Spline = React.lazy(() => import("@splinetool/react-spline"));

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isScrolled, setIsScrolled] = useState(false);
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 5) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Coca‑Cola</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <AnimatedCursor  innerSize={18}
      outerSize={18}  color='240, 230, 230'  outerAlpha={0.2}
      innerScale={0.7}
      outerScale={5} />
        <Navbar />
        <div className={styles.introDummy}></div>
        <div className={`${styles.spline}`}>
          <Suspense fallback={<div>Loading...</div>}>
            <Spline
              scene="https://prod.spline.design/cW9T8nT4Aoyqpwgd/scene.splinecode"
            />
          </Suspense>
        </div>
        <div className={`${styles.scrollIcon} ${isScrolled ? styles.hidden : ""}`}>
          <div className={styles.mouse}></div>
        </div>
        <IntroSection />
       
        {/* <HistorySection/> */}
     
        <Showcase />
      
        <ProductSection />
        <Footer/>
      </main>
    </>
  );
}
